name: Semgrep Security Scan

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    
    # Skip Dependabot PRs (optional)
    if: github.actor != 'dependabot[bot]'
    
    container:
      image: semgrep/semgrep
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis
      
      - name: Run Semgrep with Java security rulesets
        run: |
          semgrep scan \
            --config=auto \
            --config=p/security-audit \
            --config=p/owasp-top-ten \
            --config=p/java \
            --sarif \
            --output=semgrep.sarif
        env:
          # Optional: Connect to Semgrep Cloud for advanced features
          # SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_RULES: p/security-audit p/owasp-top-ten p/java
      
      - name: Upload Semgrep results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
